export const metadata = {
  title: "Imole.dev",
  description: "Generated by Next.js",
};

import "@/app/tailwind.css";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/builtbyimole-logo.svg" type="image/svg+xml" />
      </head>

      <body>{children}</body>
    </html>
  );
}